name: stream-subscriber
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyqt=5
  - pygobject
  - gstreamer
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - gst-libav
  - pyyaml
  - pip
  - pip:
    - influxdb-client
    - typing-extensions
    - fastapi
    - "uvicorn[standard]"
    - pydantic
    - annotated-doc

